# Generated by Django 4.1.7 on 2023-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometricApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField(blank=True, default=-1)),
            ],
        ),
    ]
