# Generated by Django 4.1.7 on 2023-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometricApi', '0002_patientidmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientidmapping',
            name='finger_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='patientidmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
