# Generated by Django 4.1.7 on 2023-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometricApi', '0003_patientidmapping_finger_id_alter_patientidmapping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientidmapping',
            name='finger_id',
            field=models.IntegerField(unique=True),
        ),
    ]
