# Generated by Django 4.1.7 on 2023-06-02 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=100)),
                ('diseases', models.CharField(blank=True, max_length=1000)),
                ('allergies', models.CharField(blank=True, max_length=1000)),
                ('height', models.IntegerField(blank=True, default=0)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='patientapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='patientapp.patient')),
            ],
        ),
    ]
