# Generated by Django 4.1.7 on 2023-03-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AlterField(
            model_name='fingerprintdata',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_data', to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='allergies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='patientapp.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
