# Generated by Django 4.1.7 on 2023-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_remove_patient_age_alter_fingerprintdata_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintdata',
            name='fingerprint_data',
            field=models.TextField(),
        ),
    ]
