# Generated by Django 4.1.7 on 2023-03-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_alter_fingerprintdata_fingerprint_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='patientapp.patient'),
        ),
    ]
