# Generated by Django 4.1.7 on 2023-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
