# Generated by Django 4.1.7 on 2023-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_alter_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fingerprintdata',
            name='fingerprint_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='diseases',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
