# Generated by Django 4.1.7 on 2023-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_alter_emergencycontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
