# Generated by Django 4.1.7 on 2023-03-26 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_alter_medicaldata_height_alter_medicaldata_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
