# Generated by Django 4.1.7 on 2023-04-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0010_alter_patient_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FingerprintData',
        ),
    ]
