# Generated by Django 4.1.7 on 2023-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientapp", "0011_delete_fingerprintdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldata",
            name="allergies",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="diseases",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=1000),
        ),
    ]
